### ISSUE TITLE
Should the default installation work automatically?

### ISSUE THREAD

**Issue by eduardobona** [antidot-framework/antidot-starter#3]
On access 'http://localhost:9000' after simple instalattion:

[Sun Apr 21 14:44:44 2019] PHP Fatal error:  Uncaught Zend\Config\Exception\RuntimeException: You didn't specify a Yaml callback decoder in /private/var/www/labs/antidot/vendor/zendframework/zend-config/src/Reader/Yaml.php:93
Stack trace:
#0 /private/var/www/labs/antidot/vendor/zendframework/zend-config/src/Factory.php(117): Zend\Config\Reader\Yaml->fromFile('/private/var/ww...')
#1 /private/var/www/labs/antidot/vendor/zendframework/zend-config/src/Factory.php(141): Zend\Config\Factory::fromFile('/private/var/ww...', false, false)
#2 /private/var/www/labs/antidot/vendor/zendframework/zend-config-aggregator/src/ZendConfigProvider.php(43): Zend\Config\Factory::fromFiles(Array)
#3 /private/var/www/labs/antidot/vendor/zendframework/zend-config-aggregator/src/ConfigAggregator.php(217): Zend\ConfigAggregator\ZendConfigProvider->__invoke()
#4 /private/var/www/labs/antidot/vendor/zendframework/zend-config-aggregator/src/ConfigAggregator.php(73): Zend\ConfigAggregator\ConfigAggregator->loadConfigFromProviders(Array)
#5 /private/var/www/labs/antidot/config/config in /private/var/www/labs/antidot/vendor/zendframework/zend-config/src/Reader/Yaml.php on line 93
[Sun Apr 21 14:44:44 2019] ::1:49248 [200]: / - Uncaught Zend\Config\Exception\RuntimeException: You didn't specify a Yaml callback decoder in /private/var/www/labs/antidot/vendor/zendframework/zend-config/src/Reader/Yaml.php:93
Stack trace:
#0 /private/var/www/labs/antidot/vendor/zendframework/zend-config/src/Factory.php(117): Zend\Config\Reader\Yaml->fromFile('/private/var/ww...')
#1 /private/var/www/labs/antidot/vendor/zendframework/zend-config/src/Factory.php(141): Zend\Config\Factory::fromFile('/private/var/ww...', false, false)
#2 /private/var/www/labs/antidot/vendor/zendframework/zend-config-aggregator/src/ZendConfigProvider.php(43): Zend\Config\Factory::fromFiles(Array)
#3 /private/var/www/labs/antidot/vendor/zendframework/zend-config-aggregator/src/ConfigAggregator.php(217): Zend\ConfigAggregator\ZendConfigProvider->__invoke()
#4 /private/var/www/labs/antidot/vendor/zendframework/zend-config-aggregator/src/ConfigAggregator.php(73): Zend\ConfigAggregator\ConfigAggregator->loadConfigFromProviders(Array)
#5 /private/var/www/labs/antidot/config/config in /private/var/www/labs/antidot/vendor/zendframework/zend-config/src/Reader/Yaml.php on line 93

**Comment by kpicaza** [comment]
it looks like you don't have the `yaml` extension installed https://pecl.php.net/package/yaml. I have to add it as a dependency in the `composer.json` file. 

Thanks for reporting

**Comment by kpicaza** [comment]
Yes, I can ensure it, you need the yaml extension enabled in your PHP installation. I create a pull request to add the requirement to composer.

**Comment by kpicaza** [comment]
At this moment, `yaml` extension is required in the starter because the default config is made by `yaml` files: `config/services/dependencies.prod.yaml` and `config/services/dependencies.prod.yaml`. You can avoid this by parsing default config in PHP. 

I agree with you that it should not be required since it cuts the freedom of the user in the type of configuration that he/she wants to apply.

As an enhancement, we can add a question in create-project command that asks the user the config type to install, this way the user will choose between de different config typed allowed by the framework.
