### ISSUE TITLE
initial application with error

### ISSUE THREAD

**Issue by aercioneiva** [antidot-framework/antidot-starter#5]
Uncaught Aura\Di\Exception\ServiceNotFound: Service not defined: 'Antidot\Application\Http\Application' in /home/aercio/Área de Trabalho/teste-php/vendor/aura/di/src/Exception.php:61

Stack trace:
#0 /home/aercio/Área de Trabalho/teste-php/vendor/aura/di/src/Container.php(288): Aura\Di\Exception::serviceNotFound('Antidot\\Applica...')
#1 /home/aercio/Área de Trabalho/teste-php/vendor/aura/di/src/Container.php(268): Aura\Di\Container->getServiceInstance('Antidot\\Applica...')
#2 /home/aercio/Área de Trabalho/teste-php/public/index.php(22): Aura\Di\Container->get('Antidot\\Applica...')
#3 /home/aercio/Área de Trabalho/teste-php/public/index.php(28): {closure}()
#4 {main}
  thrown in /home/aercio/Área de Trabalho/teste-php/vendor/aura/di/src/Exception.php on line 61
[Thu May 16 16:23:20 2019] 127.0.0.1:36982 [500]: / - Uncaught Aura\Di\Exception\ServiceNotFound: Service not defined: 'Antidot\Application\Http\Application' in /home/aercio/Área de Trabalho/teste-php/vendor/aura/di/src/Exception.php:61
Stack trace:
#0 /home/aercio/Área de Trabalho/teste-php/vendor/aura/di/src/Container.php(288): Aura\Di\Exception::serviceNotFound('Antidot\\Applica...')
#1 /home/aercio/Área de Trabalho/teste-php/vendor/aura/di/src/Container.php(268): Aura\Di\Container->getServiceInstance('Antidot\\Applica...')
#2 /home/aercio/Área de Trabalho/teste-php/public/index.php(22): Aura\Di\Container->get('Antidot\\Applica...')
#3 /home/aercio/Área de Trabalho/teste-php/public/index.php(28): {closure}()
#4 {main}
  thrown in /home/aercio/Área de Trabalho/teste-php/vendor/aura/di/src/Exception.php on line 61

**Comment by kpicaza** [comment]
Did you install the starter using `composer create-project` command?

**Comment by aercioneiva** [comment]
Yes, i did

**Comment by kpicaza** [comment]
Can you attach `config/config.php` file? and can you add some more information like php version, php modules and if the error happens running console command or in an http request

**Comment by aercioneiva** [comment]
Im using php 7.2 on ubuntu and I have all modules to installer any framework. this error occurs when I make an http request
[config.php.txt](https://github.com/antidot-framework/antidot-starter/files/3189295/config.php.txt

**Comment by kpicaza** [comment]
I say your version of file, not the repository's version, after `create-project` command it should automatically install all config providers inside `config/config.php` file, and the file should look something like this, watching your error, seems like that this process was not executed.

```php
<?php

declare(strict_types=1);

use Antidot\SymfonyConfigTranslator\Container\Config\ConfigAggregator;
use Zend\ConfigAggregator\ArrayProvider;
use Zend\ConfigAggregator\PhpFileProvider;
use Zend\ConfigAggregator\ZendConfigProvider;

// To enable or disable caching, set the `ConfigAggregator::ENABLE_CACHE` boolean in
// `config/autoload/local.php`.
$cacheConfig = [
    'config_cache_path' => 'var/cache/config-cache.php',
];

$aggregator = new ConfigAggregator([
    \WShafer\PSR11MonoLog\ConfigProvider::class,
    \Antidot\Event\Container\Config\ConfigProvider::class,
    \Antidot\Logger\Container\Config\ConfigProvider::class,
    \Antidot\DevTools\Container\Config\ConfigProvider::class,
    \Antidot\Cli\Container\Config\ConfigProvider::class,
    \Antidot\Aura\Router\Container\Config\ConfigProvider::class,
    \Antidot\Container\Config\ConfigProvider::class,
    \Zend\HttpHandlerRunner\ConfigProvider::class,
    // Load application config in a pre-defined order in such a way that local settings
    // overwrite global settings. (Loaded as first to last):
    //   - `*.php`
    //   - `*.global.php`
    //   - `*.local.php`
    //   - `*.dev.php`
    //   - `*.yaml`
    //   - `*.global.yaml`
    //   - `*.local.yaml`
    //   - `*.dev.yaml`
    new PhpFileProvider(realpath(__DIR__).'/services/{{,*.}prod,{,*.}local,{,*.}dev}.php'),
    new ZendConfigProvider(realpath(__DIR__).'/services/{{,*.}prod,{,*.}local,{,*.}dev}.yaml'),
    new ArrayProvider($cacheConfig),
], $cacheConfig['config_cache_path']);

return $aggregator->getMergedConfig();
```

**Comment by aercioneiva** [comment]
this is my config.php, I installed in two PC and happens the same errors. both ubuntu 16.04

<?php

declare(strict_types=1);

use Antidot\SymfonyConfigTranslator\Container\Config\ConfigAggregator;
use Zend\ConfigAggregator\ArrayProvider;
use Zend\ConfigAggregator\PhpFileProvider;
use Zend\ConfigAggregator\ZendConfigProvider;

// To enable or disable caching, set the `ConfigAggregator::ENABLE_CACHE` boolean in
// `config/autoload/local.php`.
$cacheConfig = [
    'config_cache_path' => 'var/cache/config-cache.php',
];

$aggregator = new ConfigAggregator([
    // Load application config in a pre-defined order in such a way that local settings
    // overwrite global settings. (Loaded as first to last):
    //   - `*.php`
    //   - `*.global.php`
    //   - `*.local.php`
    //   - `*.dev.php`
    //   - `*.yaml`
    //   - `*.global.yaml`
    //   - `*.local.yaml`
    //   - `*.dev.yaml`
    new PhpFileProvider(realpath(__DIR__).'/services/{{,*.}prod,{,*.}local,{,*.}dev}.php'),
    new ZendConfigProvider(realpath(__DIR__).'/services/{{,*.}prod,{,*.}local,{,*.}dev}.yaml'),
    new ArrayProvider($cacheConfig),
], $cacheConfig['config_cache_path']);

return $aggregator->getMergedConfig();

**Comment by aercioneiva** [comment]
I copied your config to my project but happens the same error

**Comment by aercioneiva** [comment]
![error](https://user-images.githubusercontent.com/8753113/57942036-da119380-78a6-11e9-8683-f798ab919544.png)

**Comment by kpicaza** [comment]
I can't reproduce the error, Can you try the following workaround?

```bash
cd {path to antidot app}
cp config/services/dependencies.dev.yaml.dist config/services/dependencies.dev.yaml
rm -rf var/cache/*
rm -rf vendor composer.lock
composer create-project
php -S 127.0.0.1:8000 -t public
```

**Comment by aercioneiva** [comment]
now. it worked with this tutorial

**Comment by kpicaza** [comment]
try removing `config/services/dependencies.dev.yaml` file, the reboot php server and check if error happens again please, and thanks by dedicating your time reporting the issue :-D

**Comment by aercioneiva** [comment]
I did, and the erro did not happen again

**Comment by kpicaza** [comment]
Ok, do you remember installation steps that you followed when the error did occur? 

I always install it following the documentation at https://antidotfw.io and it works great, it seems like you had some issue executing the create-project command in your system.

```bash
composer create-project antidot-fw/antidot-framework-starter:dev-master project-name
cd project-name
php -S 127.0.0.1:8000 -t public
```

**Comment by aercioneiva** [comment]
I followed the same tutorial

**Comment by kpicaza** [comment]
If you try my last snippet, the error happens again?

If yes, maybe there is some issue installing it automatically in ubuntu 16.04, I will try it with a virtual machine

**Comment by aercioneiva** [comment]
I tried now, and the error happened again

**Comment by kpicaza** [comment]
Thanks for your report, this is a heavy bug related to package dependencies 

![image](https://user-images.githubusercontent.com/1093654/57947816-393fca00-78e0-11e9-8030-23417947b101.png)

I'll open a new issue with the bugfix

**Comment by aercioneiva** [comment]
thanks for your support

**Comment by kpicaza** [comment]
Issue Fixed!!! Thanks for contributing.  ;-D. 

If you try again it should work correctly

**Comment by aercioneiva** [comment]
very good, it works!
